import type {components} from '../generated/api';

type Project = components['schemas']['Project'];
type Workspace = any;
const key='presentation.mock.workspace';
const seed=(): Workspace => ({project_id:'demo-project',sku:'DEMO_ASTMF136_HINGED_RING_3PCS',project_name:'Synthetic Demo Presentation',overall_status:'queued',current_stage:'product_truth',created_at:new Date().toISOString(), product_truth:{project_id:'demo-project',sku:'DEMO_ASTMF136_HINGED_RING_3PCS',product_name:'Demo ASTM F136 Titanium Hinged Ring 3PCS',category:'piercing jewelry',material:{base:'ASTM F136 implant-grade titanium',finish:'18K Gold PVD'},dimensions:{gauges:['18G','20G'],inner_diameter:'8mm'},variants:[{variant_id:'GOLD-3PCS',included_count:3}],package_contents:['classic hoop','double-layer hoop','CZ accent hoop'],product_features:['hinged closure','multi-wear set'],verified_claims:[{kind:'CLAIM',text:'ASTM F136 implant-grade titanium',source:'examples/demo_sku/product.json'}],product_images:['examples/demo_sku/assets/product.svg'],source:['examples/demo_sku/product.json'],version:1},competitor_insight:undefined,strategy:undefined});
const read=()=>JSON.parse(localStorage.getItem(key)||'null')||seed(); const write=(x:Workspace)=>localStorage.setItem(key,JSON.stringify(x));
export const mockApi={
  async listProjects(){const x=read(); return [x as Project]},
  async getProject(){return read()},
  async getProductTruth(){return read().product_truth},
  async updateProductTruth(value:any){const x=read(); x.product_truth={...value,version:(x.product_truth?.version||0)+1}; write(x); return x.product_truth},
  async getCompetitors(){return read().competitors||[]},
  async startResearch(urls:string[]){const x=read(); x.research={job_id:'research-1',status:'completed',competitor_ids:urls.map((_,i)=>`competitor-${i+1}`)}; x.competitors=urls.map((url,i)=>({competitor_id:`competitor-${i+1}`,url,title:`Competitor sample ${i+1}`,bullet_points:['Visible assortment','Material positioning'],rating:4.3,price:19.99,reviews:[],negative_reviews:[],neutral_reviews:[],positive_reviews:[],images:[],crawl_status:'completed',raw_source:{mock:true}})); x.competitor_insight={project_id:x.project_id,purchase_drivers:['material safety','fit'],customer_pain_points:['size uncertainty'],competitor_claims:['hypoallergenic'],competitor_strengths:['clear assortment'],competitor_weaknesses:['weak proof'],opportunity_gaps:['source-linked material proof'],priority_ranking:['material safety','fit'],evidence:x.competitors.map((c:any)=>({snapshot_id:c.competitor_id,field:'bullet_points',excerpt:c.bullet_points[0]})),confidence:.86,version:1}; x.current_stage='research'; write(x); return x.research},
  async getInsight(){return read().competitor_insight},
  async generateStrategy(){const x=read(); x.strategy={project_id:x.project_id,primary_purchase_drivers:['material safety','comfort','fit'],customer_pain_points:['skin sensitivity','size uncertainty'],core_differentiators:['ASTM F136 titanium','multi-wear set','secure hinged closure'],product_claims:['claim_f136_titanium','claim_gold_pvd'],proof_points:['catalog-backed material claim'],priority_order:['material safety','fit','comfort'],listing_mapping:{title:'identity'},image_mapping:{image_01:'identity'},video_mapping:{hook:'material safety'},version:1}; x.current_stage='strategy'; write(x); return x.strategy},
  async getStrategy(){return read().strategy},
  async generateListing(){const x=read(); x.listing={project_id:x.project_id,product_truth_version:1,insight_version:1,strategy_version:1,title:'ASTM F136 Titanium Hinged Septum Ring 3PCS',bullet_points:['Implant-grade titanium','Three wearable styles','Secure hinged closure','18G / 20G options','Gold PVD finish'],product_description:'A three-piece hinged ring set designed for clear fit and material confidence.',claims_used:['claim_f136_titanium','claim_gold_pvd'],strategy_refs:['strategy:v1'],version:1,generated_content:{title:'ASTM F136 Titanium Hinged Septum Ring 3PCS'},edited_content:null,approved_content:null,status:'pending_review'}; x.current_stage='listing'; write(x); return x.listing},
  async getListing(){return read().listing},
  async generateImagePlan(){const x=read(); x.image_plan={project_id:x.project_id,strategy_version:1,image_plan:{plan_version:'1.0.0',product_id:x.sku,strategy_summary:'Strategy-backed six-image plan',images:Array.from({length:6},(_,i)=>({image_id:`image_${String(i+1).padStart(2,'0')}`,role:['product_identity','contents','size_choice','material_evidence','multi_scene_wearing','hinge_operation_demo'][i],priority:i<3?'P0':'P1',prompt:'Strategy-backed prompt',generation_status:'queued',qa_status:'NEEDS_REVIEW',human_review_status:'pending_review'}))}}; write(x); return x.image_plan},
  async getImages(){return read().image_plan?[read().image_plan]:[]},
  async generateImages(){const x=read(); x.image_generation={job_id:'images-1',status:'completed',version:1}; write(x); return x.image_generation},
  async getVideo(){return read().video},
  async generateVideo(input:any){const x=read(); x.video={...input,project_id:x.project_id,strategy_version:1,status:'pending_review',version:1,strategy_refs:['strategy:v1'],final_prompt:input.final_prompt||'Create a concise product demonstration based on the approved strategy.'}; write(x); return x.video}
};
